server:
 port: ${port:8081}
  

# Service Endpoints

claim: 
  header:
    service:
      endpoint:
        serviceinfo: http://localhost:8080/serviceinfo
        headerinfo: http://localhost:8080/claimservice
        claiminfo: http://localhost:8080/claims/{claimId}?parts={partList}
        claimheader: http://localhost:8080/claims/{claimId}/header
        claimserviceline: http://localhost:8080/claims/{claimId}/servicelines
        claimcob: http://localhost:8080/claims/{claimId}/cob
        
        
   
  

