server:
 port: ${port:8080}
  

# Service Endpoints

claim: 
  service: 
    endpoint: 
        serviceInfo: http://localhost:8081/serviceinfo
        claimInfo: http://localhost:8081/claims/{claimId}?parts={partList}
        claimHeader: http://localhost:8081/claims/{claimId}/header
        claimServiceline: http://localhost:8081/claims/{claimId}/servicelines
        claimCob: http://localhost:8081/claims/{claimId}/cob
        
        
   
  

