server:
 port: ${port:8084}
  

# Service Endpoints

provider:
  service:
    endpoint:
      providerinfo: http://localhost:8085/providers/{providerId}
      multipleproviderinfo: http://localhost:8085/providers?identifiers={identifierList}
        
        
        
   
  id: 1
  

