server:
 port: ${port:8085}
  

# Service Endpoints

provider:
  service:
    endpoint:
      providerinfo: http://localhost:8084/providers/{providerId}
      multipleproviderinfo: http://localhost:8084/providers?identifiers={providerIdList}
        
        
        
   
  id: 1
  

