
server:
  port: ${port:8083}
spring:
  #profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: null

# SOAP WEB SERVICE URL's
facet:
  service:
    member:
      wsdl: http://abn-ode-app-037/FacetsWebServiceLibrary/FaWsvcInpGetMember_v3.asmx
      memNameSpace: http://trizetto.com/fxi/isl/FaWsvcInpGetMember_v3/GetMember_v3_MemberKey
      subNameSpace: http://trizetto.com/fxi/isl/FaWsvcInpGetMember_v3/GetMember_v3_SubscriberId
    
  config:
    identity: SVCAGENT
    region: Facets550
  memberId:
    page: 1
    size: 10
    skipRows: 0
  
    
   
     
