server:
 port: ${port:8083}
  

# Service Endpoints

member:
  service: 
      endpoint:
        memberinfo: http://localhost:8082/members/{memberId}
        subscriberinfo : http://localhost:8082/members/subscriber/{subscriberId}?groupId={groupId}&memberSuffix={memberSuffix}&asOfDate={asOfDate}
        
   
  

