server:
 port: ${port:8086}
  

# Service Endpoints

utilization:
  service:
    endpoint:
      utilizationinfo: http://localhost:8085/util/{authId}?utilFromDate={utilFromDate}&utilToDate={utilToDate}
        
        
        
   
  id: 1
  

